import dotenv from "dotenv";
dotenv.config();
export const PORT = process.env.PORT;
export const JWT_SECRET = process.env.JWT_SECRET;
export const REDIS_HOST = process.env.REDIS_HOST;
export const REDIS_PORT = process.env.REDIS_PORT;
export const REDIS_PASSWORD = process.env.REDIS_PASSWORD;
export const MAILTRAP_HOST = process.env.MAILTRAP_HOST;
export const MAILTRAP_PORT = process.env.MAILTRAP_PORT;
export const MAILTRAP_USERNAME = process.env.MAILTRAP_USERNAME;
export const MAILTRAP_PASSWORD = process.env.MAILTRAP_PASSWORD;
export const MAILTRAP_SENDEREMAIL = process.env.MAILTRAP_SENDEREMAIL;
export const BASE_URL = process.env.BASE_URL;
